In [18]:
import sys
sys.path.insert(0,'/homelocal/mrilee/git/pystareplotlib')

import os
os.environ['PROJ_LIB'] = '/homelocal/mrilee/opt/anaconda3/envs/stare-1/share/proj'

import astropy

import pystare
import starepandas
import geopandas

import matplotlib.pyplot as plt
import matplotlib.tri as tri
import cartopy
import cartopy.crs as ccrs

import pystareplotlib
import pystareplotlib.pystareplotlib as psplot

import numpy
import pandas

import pickle
import datetime

plot_options = {'projection': ccrs.PlateCarree(central_longitude=0.0)
                ,'transform': ccrs.Geodetic()}

plot_options['projection']._threshold = 0.001;

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
# geo:38.058333,-76.331667 

In [12]:
sid = pystare.from_latlon([38.058333],[-76.331667],27)
psplot.hex16(sid[0])

'0x2bf5688955c328fb'

In [15]:
sid4 = pystare.spatial_clear_to_resolution(pystare.spatial_coerce_resolution(sid,4))
psplot.hex16(sid4[0])

'0x2bf0000000000004'

In [37]:
print(hex((sid4[0] & ~31 ) >> 1 ))
print(hex(sid4[0] & ~31 ))

0x15f8000000000000
0x2bf0000000000000


In [44]:
for i in range(8):
    print(psplot.hex16((pystare.spatial_increment_from_level(0)*i) >> 1 ))

0x0000000000000000
0x0400000000000000
0x0800000000000000
0x0c00000000000000
0x1000000000000000
0x1400000000000000
0x1800000000000000
0x1c00000000000000


In [45]:
for i in range(8):
    print(psplot.hex16((pystare.spatial_increment_from_level(0)*i) ))

0x0000000000000000
0x0800000000000000
0x1000000000000000
0x1800000000000000
0x2000000000000000
0x2800000000000000
0x3000000000000000
0x3800000000000000


In [46]:
0x28/00/00/00/00/00/00/00
0q/4/3/4/3/4/3/

SyntaxError: invalid decimal literal (1010572389.py, line 2)

In [22]:
# Create the TIVs
# times = numpy.array(['2021-09-03', '2021-07-17 11:16'], dtype='datetime64')
times = numpy.array(datetime.datetime.now(),dtype='datetime64')

times = astropy.time.Time(times, scale='utc', format='datetime64')
tivs = pystare.from_julian_date(times.jd1, times.jd2,
                                scale='utc',
                                forward_res=48, reverse_res=48)
psplot.hex16(tivs[0])

'0x1f996cf66592b0c1'

In [25]:
triple = pystare.to_temporal_triple_ms(tivs)
triple

(array([2276970892134334717]),
 array([2276970892134363329]),
 array([2276970892134383613]))

In [27]:
for t in triple:
    print(numpy.datetime_as_string(pystare.to_ms_since_epoch_utc(t).astype('datetime64[ms]')))

['2022-06-10T15:25:00.585']
['2022-06-10T15:25:00.586']
['2022-06-10T15:25:00.587']


In [ ]:
hdf + sidecar -> performance like hdf alone
chunked into "our format" stare-sorted and in hdf/pkl -> faster

In [47]:
DMR++

SyntaxError: invalid syntax (1733239657.py, line 1)